sudo: false
language: node_js
node_js:
  - '8'
  - '6'
  - '4'
  - '3'
  - '2'
  - '1'
  - '0.12'
  - '0.10'
script: "npm run test-travis"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
